export const BEGIN_STRAVA_AUTH = "BEGIN_STRAVA_AUTH";
export const VALIDATE_STRAVA_TOKEN = "VALIDATE_STRAVA_TOKEN";
export const UPDATE_AUTH_TOKENS = "UPDATE_AUTH_TOKENS";
export const AUTH_START_LOG_OUT = "AUTH_START_LOG_OUT";
